apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ep-mern-kea-frontend
  name: ep-mern-kea-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ep-mern-kea-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ep-mern-kea-frontend
    spec:
      containers:
      - name: ep-mern-kea-frontend
        image: azurecontainerlorde.azurecr.io/ep-mern-kea-front:v6
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---

apiVersion: v1
kind: Service
metadata:
  name: ep-mern-kea-frontend
  labels:
    run: ep-mern-kea-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: ep-mern-kea-frontend
  type: LoadBalancer