trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
  
- task: CopyFilesOverSSH@0
  displayName: "Publish Pipeline Artifact"
  inputs:
    sshEndpoint: 'EP-Server'
    contents: '**'
    targetFolder: '/app'
    readyTimeout: '20000'

- task: SSH@0
  inputs:
    sshEndpoint: 'EP-Server'
    runOptions: 'inline'
    inline: '
    cd app; 
    sudo docker build . -t test'
    readyTimeout: '20000'
    
  

