version: '3.8'

services:

  nginx:
    depends_on:
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_DEVELOPMENT_URL=http://localhost:8080
      - REACT_APP_PROD_URL=http://207.154.228.42:3001
      - REACT_APP_ENVIRONMENT=prod
      - REACT_APP_SECRET_CODE=123

      - REACT_APP_APIKEY_GOOGLE_MAPS=AIzaSyCywB8YAGzfsCy72UJ6JaOJYIzTr84P-XA

      - REACT_APP_SECRET_KEY=AAJ-AWESOME-KEY
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - client_volume:/app/node_modules
      - client_volume:/client:/app

volumes:
  client_volume: