version: '3.8'

services:
  client:
    image: ep-mern-kea-client:latest
    container_name: ep-mern-kea-front
    # stdin_open: true
    environment:
      - REACT_APP_ENVIRONMENT=prod
      - REACT_APP_PRODUCTION_AUTH_URL=http://20.240.18.244/ms/auth
      - REACT_APP_PRODUCTION_SEARCH_SERVICE_URL=http://20.240.18.244/ms/search
      - REACT_APP_PRODUCTION_API_URL=http://20.240.18.244/api

      - REACT_APP_SECRET_CODE=123

      - REACT_APP_APIKEY_GOOGLE_MAPS=AIzaSyCywB8YAGzfsCy72UJ6JaOJYIzTr84P-XA

      - REACT_APP_SECRET_KEY = AAJ-AWESOME-KEY
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "8080:80"

