version: '3'

networks: 
  ep-mern: 
    external: true

services:
  search-service:
    image: ep-mern-kea-frontend:v1
    container_name: ep-mern-kea-frontend
    # stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_DEVELOPMENT_URL=http://localhost:8080
      - REACT_APP_PROD_URL=http://207.154.228.42:3001
      - REACT_APP_ENVIRONMENT=prod
      - REACT_APP_SECRET_CODE=123

    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /api/node_modules
      - ./api:/app
    ports:
      - "8080:8080"