apiVersion: apps/v1
kind: Deployment
metadata:
  name: ep-mern-kea-frontend  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ep-mern-kea-frontend
  template:
    metadata:
      labels:
        app: ep-mern-kea-frontend
    spec:
      containers:
      - name: ep-mern-kea-frontend
        image: azurecontainerlorde.azurecr.io/ep-mern-kea-frontend:${BUILD_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ep-mern-kea-frontend
  labels:
    run: ep-mern-kea-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: ep-mern-kea-frontend